title: ROENMI
description: Handmade products for your home by ROENMI
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
